services:
  - type: web
    name: qa-automation
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: CHROME_BINARY
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
      - key: PYTHONUNBUFFERED
        value: "1"
